"""
pkpy — Python bindings for the pkcore Rust poker analysis library.

Provides card types, hand evaluation, and Texas Hold'em game simulation.

Basic usage::

    from pkpy import Card, Cards, HoleCards, Board, Game, Outs

    # Parse individual cards
    ace = Card.parse("As")
    king = Card.parse("Kh")

    # Build a game and calculate outs
    hc = HoleCards.parse("As Kh 8d Kc")
    board = Board.parse("Ac 8h 7h 9s")
    game = Game(hc, board)
    outs = Outs.from_case_evals(game.turn_case_evals())
    print(f"Player 1 outs: {outs.len_for_player(1)}")
    print(f"Player 2 outs: {outs.len_for_player(2)}")
"""

from pkpy._pkpy import (
    KuhnCard,
    KuhnAction,
    KuhnHistory,
    KuhnInfoSet,
    KuhnState,
    KuhnStrategy,
    KuhnCfr,
    Bard,
    Board,
    Card,
    Cards,
    CaseEvals,
    Combo,
    ComboPairs,
    Combos,
    Dealer,
    Deck,
    Eval,
    FlopEval,
    ForcedBets,
    Game,
    HandRank,
    HandRankClass,
    HoleCards,
    HUPResult,
    IndexCardMap,
    Outs,
    Player,
    PlayerNoCell,
    PlayerAction,
    PlayerState,
    Pluribus,
    PokerSession,
    PluribusEvent,
    Qualifier,
    Rank,
    SeatEquity,
    SeatNoCell,
    SeatsNoCell,
    Seatbit,
    SessionStep,
    SevenFiveBCM,
    Stack,
    Suit,
    TableAction,
    TableLog,
    TableNoCell,
    TurnEval,
    Two,
    Twos,
    Versus,
    PotWin,
    WinLoseDraw,
    Winnings,
    unique_2_card_hands,
    unique_5_card_hands,
    distinct_2_card_hands,
    distinct_5_card_hands,
)

__all__ = [
    "KuhnCard",
    "KuhnAction",
    "KuhnHistory",
    "KuhnInfoSet",
    "KuhnState",
    "KuhnStrategy",
    "KuhnCfr",
    "Bard",
    "Board",
    "Card",
    "Cards",
    "CaseEvals",
    "Combo",
    "ComboPairs",
    "Combos",
    "Dealer",
    "Deck",
    "Eval",
    "FlopEval",
    "ForcedBets",
    "Game",
    "HandRank",
    "HandRankClass",
    "HoleCards",
    "HUPResult",
    "IndexCardMap",
    "Outs",
    "Player",
    "PlayerNoCell",
    "PlayerAction",
    "PlayerState",
    "Pluribus",
    "PokerSession",
    "PluribusEvent",
    "Qualifier",
    "Rank",
    "SeatEquity",
    "SeatNoCell",
    "SeatsNoCell",
    "Seatbit",
    "SessionStep",
    "SevenFiveBCM",
    "Stack",
    "Suit",
    "TableAction",
    "TableLog",
    "TableNoCell",
    "TurnEval",
    "Two",
    "Twos",
    "Versus",
    "PotWin",
    "WinLoseDraw",
    "Winnings",
    "unique_2_card_hands",
    "unique_5_card_hands",
    "distinct_2_card_hands",
    "distinct_5_card_hands",
]
